name: 'dart_snake'
version: 0.0.4
description: The classic Snake game as a Dart web app.

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
